const feed=document.querySelector('#feed'),sort=document.querySelector('#sort');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const avatar='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"%3E%3Crect width="100" height="100" fill="%23dfe9e2"/%3E%3Ccircle cx="50" cy="36" r="18" fill="%2372807b"/%3E%3Cpath d="M15 94c4-25 17-38 35-38s31 13 35 38" fill="%2372807b"/%3E%3C/svg%3E';
const badge=active=>active?'<span class="agent-badge" role="img" aria-label="Verified agent" title="Verified agent">✓</span>':'';
const csrf=async()=>{const response=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!response.ok)throw new Error('Please sign in to interact with posts');return (await response.json()).token};
async function viewPost(card){if(!card||card.dataset.viewed==='true')return;const counter=card.querySelector('[data-views],[data-post-views]');try{const response=await fetch(`/api/listings/${encodeURIComponent(card.dataset.postId)}/view`,{method:'POST',credentials:'same-origin',cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to record post view');card.dataset.viewed='true';if(counter&&data.views!==undefined)counter.textContent=`${data.views} views`}catch(error){delete card.dataset.viewed;console.warn('StayNest view tracking failed',error.message)}}
async function likePost(card,event){event.stopPropagation();const button=event.currentTarget,liked=card.dataset.liked==='true';button.disabled=true;try{const token=await csrf();const response=await fetch(`/api/listings/${card.dataset.postId}/like`,{method:liked?'DELETE':'POST',credentials:'same-origin',headers:{'X-CSRF-Token':token}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to update like');card.dataset.liked=String(data.liked);button.classList.toggle('liked',data.liked);button.setAttribute('aria-pressed',String(data.liked));card.querySelector('[data-likes]').textContent=`${data.likes} likes`}catch(error){button.setAttribute('aria-label',error.message)}finally{button.disabled=false}}
async function load(){const response=await fetch(`/api/posts?sort=${sort.value}`,{credentials:'same-origin'});const data=await response.json();if(!response.ok){feed.innerHTML='<div class="feed-empty">Sign in and follow agents to see their posts here.<br><a class="primary small" href="/">Explore agents</a></div>';return}feed.innerHTML=data.posts.length?data.posts.map(post=>{const name=escapeHtml(`${post.firstName||''} ${post.lastName||''}`.trim()||'StayNest agent'),id=Number(post.agentId||post.agent_user_id),media=post.mediaType==='video'?`<video class="post-media" src="${escapeHtml(post.mediaUrl||'')}" controls playsinline preload="metadata"></video>`:`<img class="post-media" src="${escapeHtml(post.mediaUrl||avatar)}" alt="${escapeHtml(post.title)}" loading="lazy">`;return `<article class="post-card" data-post-id="${post.id}" data-agent-id="${id}" data-liked="${post.liked?'true':'false'}"><a class="post-byline" href="/index.html?agent=${id}&from=post" aria-label="Open ${name}'s agent profile"><img class="post-avatar" src="${escapeHtml(post.profileImageUrl||avatar)}" alt=""><div><strong>${name}${badge(post.badgeLabel)}</strong><small>${escapeHtml(post.city||'')} · ${post.mediaType==='video'?'Video tour':'Photo post'}</small></div></a>${media}<div class="post-copy"><h2>${escapeHtml(post.title)}</h2><p>${escapeHtml(post.description||'')}</p><div class="post-meta"><span>★ ${escapeHtml(post.rating||'0')} · ${escapeHtml(post.reviewCount||0)} reviews</span><span><button class="post-like-button ${post.liked?'liked':''}" data-like aria-label="Like post" aria-pressed="${Boolean(post.liked)}">♥</button> <b data-likes>${escapeHtml(post.likes||0)} likes</b> · <b data-views>${escapeHtml(post.views||0)} views</b></span></div></div></article>`}).join(''):'<div class="feed-empty">You are not following any agents yet. Visit an agent profile to follow them.<br><a class="primary small" href="/">Explore agents</a></div>';
feed.querySelectorAll('.post-card').forEach(card=>{viewPost(card);card.addEventListener('pointerenter',()=>viewPost(card),{once:true});card.querySelector('[data-like]').addEventListener('click',event=>likePost(card,event));card.addEventListener('click',event=>{if(event.target.closest('a,button,video'))return;void viewPost(card);const id=Number(card.dataset.agentId);if(id)window.location.href=`/index.html?agent=${id}&from=post`})})}
sort.addEventListener('change',load);load().catch(()=>{feed.innerHTML='<div class="feed-empty">The feed is temporarily unavailable.</div>'});
