-- StayNest rental and short-term stay platform
-- MySQL 8.0+ / InnoDB / UTC timestamps
--
-- Security notes:
-- 1. Store password hashes generated by Argon2id or bcrypt. Never store passwords.
-- 2. Store only payment-provider token/reference values. Never store PAN or CVV.
-- 3. Enforce booking overlap checks in a transaction with SELECT ... FOR UPDATE.

CREATE DATABASE IF NOT EXISTS staynest
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE staynest;

SET time_zone = '+00:00';

CREATE TABLE roles (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL UNIQUE
) ENGINE=InnoDB;

INSERT IGNORE INTO roles (name)
VALUES ('tenant'), ('agent'), ('administrator');

CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(254) NULL UNIQUE,
  phone VARCHAR(32) NULL UNIQUE,
  password_hash VARCHAR(255) NULL,
  status ENUM('pending','active','suspended','deleted') NOT NULL DEFAULT 'pending',
  email_verified_at DATETIME NULL,
  phone_verified_at DATETIME NULL,
  mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  mfa_secret_encrypted VARBINARY(512) NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT chk_user_contact CHECK (email IS NOT NULL OR phone IS NOT NULL),
  INDEX idx_users_status (status),
  INDEX idx_users_created (created_at)
) ENGINE=InnoDB;

CREATE TABLE user_roles (
  user_id BIGINT UNSIGNED NOT NULL,
  role_id TINYINT UNSIGNED NOT NULL,
  assigned_by BIGINT UNSIGNED NULL,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT fk_user_roles_assigner FOREIGN KEY (assigned_by) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE agent_subaccounts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  main_agent_user_id BIGINT UNSIGNED NOT NULL,
  subagent_user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  label VARCHAR(120) NOT NULL,
  status ENUM('pending','active','suspended','revoked') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_subaccount_main FOREIGN KEY (main_agent_user_id) REFERENCES users(id),
  CONSTRAINT fk_subaccount_user FOREIGN KEY (subagent_user_id) REFERENCES users(id),
  INDEX idx_subaccount_main (main_agent_user_id, status)
) ENGINE=InnoDB;

CREATE TABLE agent_subaccount_permissions (
  subaccount_id BIGINT UNSIGNED NOT NULL,
  permission_key VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (subaccount_id, permission_key),
  CONSTRAINT fk_subpermission_account FOREIGN KEY (subaccount_id) REFERENCES agent_subaccounts(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE user_profiles (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  display_name VARCHAR(160) NULL,
  avatar_url VARCHAR(2048) NULL,
  bio TEXT NULL,
  preferred_language VARCHAR(10) NOT NULL DEFAULT 'en',
  preferred_currency CHAR(3) NOT NULL DEFAULT 'USD',
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  address_line1 VARCHAR(190) NULL,
  address_line2 VARCHAR(190) NULL,
  city VARCHAR(100) NULL,
  country_code CHAR(2) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE agent_profiles (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  phone VARCHAR(32) NULL,
  bio TEXT NULL,
  profile_image_url VARCHAR(2048) NULL,
  followers_count INT UNSIGNED NOT NULL DEFAULT 0,
  following_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE agent_follows (
  follower_user_id BIGINT UNSIGNED NOT NULL,
  agent_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (follower_user_id, agent_user_id),
  CONSTRAINT fk_follow_follower FOREIGN KEY (follower_user_id) REFERENCES users(id),
  CONSTRAINT fk_follow_agent FOREIGN KEY (agent_user_id) REFERENCES users(id),
  CONSTRAINT chk_follow_self CHECK (follower_user_id <> agent_user_id)
) ENGINE=InnoDB;

CREATE TABLE identity_verifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  document_type ENUM('national_id','passport','drivers_license','business_license') NOT NULL,
  document_country CHAR(2) NULL,
  document_last4 CHAR(4) NULL,
  document_file_key VARCHAR(512) NOT NULL,
  status ENUM('pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  rejection_reason VARCHAR(500) NULL,
  expires_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_verification_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_verification_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
  INDEX idx_verifications_review (status, created_at),
  INDEX idx_verifications_user (user_id, status)
) ENGINE=InnoDB;

CREATE TABLE businesses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  legal_name VARCHAR(190) NOT NULL,
  registration_number VARCHAR(100) NULL,
  license_number VARCHAR(100) NULL,
  tax_identifier VARCHAR(100) NULL,
  country_code CHAR(2) NULL,
  status ENUM('pending','verified','rejected') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_business_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
  INDEX idx_business_owner (owner_user_id)
) ENGINE=InnoDB;

CREATE TABLE property_types (
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

INSERT IGNORE INTO property_types (name)
VALUES ('apartment'), ('house'), ('room'), ('commercial'), ('short_stay');

CREATE TABLE listings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  agent_user_id BIGINT UNSIGNED NULL,
  property_type_id SMALLINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  status ENUM('draft','pending_review','published','unpublished','rejected','archived') NOT NULL DEFAULT 'draft',
  booking_mode ENUM('request','instant') NOT NULL DEFAULT 'request',
  rental_mode ENUM('short_term','long_term','both') NOT NULL DEFAULT 'short_term',
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  nightly_price DECIMAL(12,2) NULL,
  monthly_price DECIMAL(12,2) NULL,
  yearly_price DECIMAL(12,2) NULL,
  cleaning_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  service_fee_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  bedrooms TINYINT UNSIGNED NOT NULL DEFAULT 0,
  bathrooms DECIMAL(4,1) NOT NULL DEFAULT 1,
  max_guests SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  address_line1 VARCHAR(190) NOT NULL,
  neighborhood VARCHAR(120) NULL,
  city VARCHAR(100) NOT NULL,
  region VARCHAR(100) NULL,
  country_code CHAR(2) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  approximate_latitude DECIMAL(10,7) NULL,
  approximate_longitude DECIMAL(10,7) NULL,
  house_rules JSON NULL,
  cancellation_policy ENUM('flexible','moderate','strict','custom') NOT NULL DEFAULT 'moderate',
  min_stay_nights SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  max_stay_nights SMALLINT UNSIGNED NULL,
  average_rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  review_count INT UNSIGNED NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_listing_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
  CONSTRAINT fk_listing_agent FOREIGN KEY (agent_user_id) REFERENCES users(id),
  CONSTRAINT fk_listing_type FOREIGN KEY (property_type_id) REFERENCES property_types(id),
  CONSTRAINT chk_listing_prices CHECK (nightly_price IS NOT NULL OR monthly_price IS NOT NULL OR yearly_price IS NOT NULL),
  INDEX idx_listings_discovery (status, city, property_type_id, rental_mode),
  INDEX idx_listings_geo (latitude, longitude),
  INDEX idx_listings_price (status, nightly_price, monthly_price, yearly_price),
  FULLTEXT KEY ft_listings_search (title, description, neighborhood, city)
) ENGINE=InnoDB;

CREATE TABLE listing_amenities (
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE listing_amenity_map (
  listing_id BIGINT UNSIGNED NOT NULL,
  amenity_id SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (listing_id, amenity_id),
  CONSTRAINT fk_lam_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT fk_lam_amenity FOREIGN KEY (amenity_id) REFERENCES listing_amenities(id)
) ENGINE=InnoDB;

CREATE TABLE listing_media (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  media_type ENUM('image','video') NOT NULL DEFAULT 'image',
  storage_key VARCHAR(512) NOT NULL,
  public_url VARCHAR(2048) NOT NULL,
  caption VARCHAR(255) NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_media_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  INDEX idx_media_listing (listing_id, sort_order)
) ENGINE=InnoDB;

CREATE TABLE listing_likes (
  user_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, listing_id),
  CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_like_listing FOREIGN KEY (listing_id) REFERENCES listings(id)
) ENGINE=InnoDB;

CREATE TABLE listing_views (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  viewer_user_id BIGINT UNSIGNED NULL,
  viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_view_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT fk_view_user FOREIGN KEY (viewer_user_id) REFERENCES users(id),
  INDEX idx_views_listing (listing_id, viewed_at)
) ENGINE=InnoDB;

CREATE TABLE listing_availability (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  available_from DATE NOT NULL,
  available_to DATE NOT NULL,
  status ENUM('available','blocked') NOT NULL DEFAULT 'available',
  nightly_price DECIMAL(12,2) NULL,
  note VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_availability_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT chk_availability_dates CHECK (available_to > available_from),
  INDEX idx_availability_lookup (listing_id, available_from, available_to, status)
) ENGINE=InnoDB;

CREATE TABLE pricing_rules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  adjustment_type ENUM('fixed','percent') NOT NULL,
  adjustment_value DECIMAL(12,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pricing_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT chk_pricing_dates CHECK (ends_on >= starts_on),
  INDEX idx_pricing_dates (listing_id, starts_on, ends_on)
) ENGINE=InnoDB;

CREATE TABLE saved_listings (
  user_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, listing_id),
  CONSTRAINT fk_saved_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_saved_listing FOREIGN KEY (listing_id) REFERENCES listings(id)
) ENGINE=InnoDB;

CREATE TABLE search_alerts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  filters JSON NOT NULL,
  frequency ENUM('instant','daily','weekly') NOT NULL DEFAULT 'daily',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_sent_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alert_user FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_alerts_delivery (is_active, frequency, last_sent_at)
) ENGINE=InnoDB;

CREATE TABLE bookings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_code CHAR(12) NOT NULL UNIQUE,
  listing_id BIGINT UNSIGNED NOT NULL,
  guest_user_id BIGINT UNSIGNED NOT NULL,
  host_user_id BIGINT UNSIGNED NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  guests SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  currency CHAR(3) NOT NULL,
  nightly_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  nights SMALLINT UNSIGNED NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  cleaning_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  service_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL,
  status ENUM('pending','payment_pending','confirmed','declined','cancelled','completed','disputed') NOT NULL DEFAULT 'pending',
  payment_status ENUM('unpaid','authorized','paid','partially_refunded','refunded','failed') NOT NULL DEFAULT 'unpaid',
  cancellation_reason VARCHAR(500) NULL,
  confirmed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_booking_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT fk_booking_guest FOREIGN KEY (guest_user_id) REFERENCES users(id),
  CONSTRAINT fk_booking_host FOREIGN KEY (host_user_id) REFERENCES users(id),
  CONSTRAINT chk_booking_dates CHECK (check_out > check_in),
  CONSTRAINT chk_booking_total CHECK (total_amount >= 0),
  INDEX idx_booking_listing_dates (listing_id, check_in, check_out, status),
  INDEX idx_booking_guest (guest_user_id, created_at),
  INDEX idx_booking_host (host_user_id, status)
) ENGINE=InnoDB;

CREATE TABLE booking_date_locks (
  listing_id BIGINT UNSIGNED NOT NULL,
  stay_date DATE NOT NULL,
  booking_id BIGINT UNSIGNED NOT NULL,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (listing_id, stay_date),
  CONSTRAINT fk_lock_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT fk_lock_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  INDEX idx_locks_expiry (expires_at)
) ENGINE=InnoDB;

CREATE TABLE payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(40) NOT NULL,
  provider_payment_id VARCHAR(190) NOT NULL,
  provider_customer_id VARCHAR(190) NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  status ENUM('pending','authorized','succeeded','failed','refunded','partially_refunded') NOT NULL,
  paid_at DATETIME NULL,
  raw_event_id VARCHAR(190) NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  UNIQUE KEY uq_provider_payment (provider, provider_payment_id),
  INDEX idx_payments_status (status, created_at)
) ENGINE=InnoDB;

CREATE TABLE refunds (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_id BIGINT UNSIGNED NOT NULL,
  provider_refund_id VARCHAR(190) NULL UNIQUE,
  amount DECIMAL(12,2) NOT NULL,
  reason VARCHAR(500) NULL,
  status ENUM('pending','succeeded','failed') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
) ENGINE=InnoDB;

CREATE TABLE payouts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  host_user_id BIGINT UNSIGNED NOT NULL,
  booking_id BIGINT UNSIGNED NULL,
  provider VARCHAR(40) NOT NULL,
  provider_payout_id VARCHAR(190) NULL UNIQUE,
  amount DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  platform_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('pending','in_transit','paid','failed','cancelled') NOT NULL DEFAULT 'pending',
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payout_host FOREIGN KEY (host_user_id) REFERENCES users(id),
  CONSTRAINT fk_payout_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  INDEX idx_payout_host (host_user_id, status, created_at)
) ENGINE=InnoDB;

CREATE TABLE reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  author_user_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  cleanliness_rating TINYINT UNSIGNED NULL,
  communication_rating TINYINT UNSIGNED NULL,
  location_rating TINYINT UNSIGNED NULL,
  comment TEXT NULL,
  status ENUM('published','hidden','reported') NOT NULL DEFAULT 'published',
  host_reply TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  CONSTRAINT fk_review_author FOREIGN KEY (author_user_id) REFERENCES users(id),
  CONSTRAINT fk_review_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT uq_review_booking UNIQUE (booking_id, author_user_id),
  CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),
  INDEX idx_reviews_listing (listing_id, status, created_at)
) ENGINE=InnoDB;

CREATE TABLE conversations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  listing_id BIGINT UNSIGNED NULL,
  booking_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_conversation_listing FOREIGN KEY (listing_id) REFERENCES listings(id),
  CONSTRAINT fk_conversation_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
) ENGINE=InnoDB;

CREATE TABLE conversation_members (
  conversation_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  last_read_at DATETIME NULL,
  PRIMARY KEY (conversation_id, user_id),
  CONSTRAINT fk_member_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
  CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE messages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id BIGINT UNSIGNED NOT NULL,
  sender_user_id BIGINT UNSIGNED NOT NULL,
  body TEXT NOT NULL,
  attachment_key VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
  CONSTRAINT fk_message_sender FOREIGN KEY (sender_user_id) REFERENCES users(id),
  INDEX idx_messages_conversation (conversation_id, created_at)
) ENGINE=InnoDB;

CREATE TABLE notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  data JSON NULL,
  read_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_notifications_user (user_id, read_at, created_at)
) ENGINE=InnoDB;

CREATE TABLE notification_deliveries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(60) NOT NULL,
  status ENUM('pending','sent','in_app','failed') NOT NULL DEFAULT 'pending',
  error_message VARCHAR(500) NULL,
  metadata JSON NULL,
  delivered_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delivery_user FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_delivery_status (status, created_at)
) ENGINE=InnoDB;

CREATE TABLE disputes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  opened_by BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('open','investigating','resolved','closed') NOT NULL DEFAULT 'open',
  resolution TEXT NULL,
  assigned_to BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_dispute_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  CONSTRAINT fk_dispute_opener FOREIGN KEY (opened_by) REFERENCES users(id),
  CONSTRAINT fk_dispute_assignee FOREIGN KEY (assigned_to) REFERENCES users(id),
  INDEX idx_disputes_queue (status, created_at)
) ENGINE=InnoDB;

CREATE TABLE audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(60) NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  ip_address VARBINARY(16) NULL,
  user_agent VARCHAR(512) NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id),
  INDEX idx_audit_entity (entity_type, entity_id, created_at),
  INDEX idx_audit_actor (actor_user_id, created_at)
) ENGINE=InnoDB;

-- Example transactional overlap check for a new booking.
-- The API must run this inside a transaction and insert date locks before payment:
--
-- SELECT id
-- FROM bookings
-- WHERE listing_id = :listing_id
--   AND status IN ('pending','payment_pending','confirmed')
--   AND check_in < :requested_check_out
--   AND check_out > :requested_check_in
-- FOR UPDATE;
--
-- Then create one booking_date_locks row per requested stay date. A duplicate
-- primary key means another checkout already owns that date.
